#!/bin/sh
# Launch sway as the Foyer multi-output compositor (F1 foundation).
# Generates a minimal config from FOYER_VIDEO_OUTPUT, then execs sway.
# Still one Welcome Chromium on the chosen head; other outputs off.
set -eu
ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
CONF="${XDG_RUNTIME_DIR:-/tmp}/foyer-sway.conf"
KIOSK_SH="${ROOT}/scripts/foyer-kiosk.sh"

mkdir -p "${XDG_RUNTIME_DIR:-/tmp}"

{
  printf '%s\n' \
    '# Generated by foyer-kiosk-sway.sh — do not edit by hand.' \
    'default_border none' \
    'default_floating_border none' \
    'font pango:monospace 1' \
    'seat * hide_cursor 1' \
    'bar {' \
    '    mode invisible' \
    '}' \
    'for_window [app_id="chromium"] fullscreen enable' \
    'for_window [app_id="chromium-browser"] fullscreen enable' \
    'for_window [class="Chromium"] fullscreen enable' \
    'for_window [class="Chromium-browser"] fullscreen enable'

  if [ -n "${FOYER_VIDEO_OUTPUT:-}" ]; then
    # DRM connector names are alphanumeric / . _ - (from /sys/class/drm).
    case "$FOYER_VIDEO_OUTPUT" in
      *[!A-Za-z0-9._-]*)
        printf '%s\n' "foyer-kiosk-sway: ignoring unsafe FOYER_VIDEO_OUTPUT" >&2
        ;;
      *)
        # Single-Welcome mode (F1): blank every head, then enable the Setup pick.
        # F3 can later enable a second output under this same compositor.
        printf '%s\n' 'output * disable'
        printf 'output %s enable\n' "$FOYER_VIDEO_OUTPUT"
        ;;
    esac
  fi

  printf 'exec %s\n' "$KIOSK_SH"
} >"$CONF"

exec /usr/bin/sway -c "$CONF"
