/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ApiPeerRouteImport } from './routes/api/peer'
import { Route as PlayDisplayIdRouteImport } from './routes/play.$displayId'
import { Route as ApiPeerStatusRouteImport } from './routes/api/peer.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerRoute = ApiPeerRouteImport.update({
  id: '/api/peer',
  path: '/api/peer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDisplayIdRoute = PlayDisplayIdRouteImport.update({
  id: '/play/$displayId',
  path: '/play/$displayId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerStatusRoute = ApiPeerStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiPeerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/peer': typeof ApiPeerRouteWithChildren
  '/play/$displayId': typeof PlayDisplayIdRoute
  '/api/peer/status': typeof ApiPeerStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/peer': typeof ApiPeerRouteWithChildren
  '/play/$displayId': typeof PlayDisplayIdRoute
  '/api/peer/status': typeof ApiPeerStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/peer': typeof ApiPeerRouteWithChildren
  '/play/$displayId': typeof PlayDisplayIdRoute
  '/api/peer/status': typeof ApiPeerStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/config' | '/api/peer' | '/play/$displayId' | '/api/peer/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/api/peer' | '/play/$displayId' | '/api/peer/status'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/api/peer'
    | '/play/$displayId'
    | '/api/peer/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  ApiPeerRoute: typeof ApiPeerRouteWithChildren
  PlayDisplayIdRoute: typeof PlayDisplayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peer': {
      id: '/api/peer'
      path: '/api/peer'
      fullPath: '/api/peer'
      preLoaderRoute: typeof ApiPeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$displayId': {
      id: '/play/$displayId'
      path: '/play/$displayId'
      fullPath: '/play/$displayId'
      preLoaderRoute: typeof PlayDisplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peer/status': {
      id: '/api/peer/status'
      path: '/status'
      fullPath: '/api/peer/status'
      preLoaderRoute: typeof ApiPeerStatusRouteImport
      parentRoute: typeof ApiPeerRoute
    }
  }
}

interface ApiPeerRouteChildren {
  ApiPeerStatusRoute: typeof ApiPeerStatusRoute
}

const ApiPeerRouteChildren: ApiPeerRouteChildren = {
  ApiPeerStatusRoute: ApiPeerStatusRoute,
}

const ApiPeerRouteWithChildren =
  ApiPeerRoute._addFileChildren(ApiPeerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  ApiPeerRoute: ApiPeerRouteWithChildren,
  PlayDisplayIdRoute: PlayDisplayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
